 **BlinkIT Grocery Raw Data download from kaggle**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("BlinkIT Grocery Raw Data.xlsx")
df.head()

,Item Fat Content,Item Identifier,Item Type,Outlet Establishment Year,Outlet Identifier,Outlet Location Type,Outlet Size,Outlet Type,Item Visibility,Item Weight,Sales,Rating
0,Regular,FDX32,Fruits and Vegetables,2012,OUT049,Tier 1,Medium,Supermarket Type1,0.100014,15.10,145.4786,5.0
1,Low Fat,NCB42,Health and Hygiene,2022,OUT018,Tier 3,Medium,Supermarket Type2,0.008596,11.80,115.3492,5.0
2,Regular,FDR28,Frozen Foods,2016,OUT046,Tier 1,Small,Supermarket Type1,0.025896,13.85,165.0210,5.0
3,Regular,FDL50,Canned,2014,OUT013,Tier 3,High,Supermarket Type1,0.042278,12.15,126.5046,5.0
4,Low Fat,DRI25,Soft Drinks,2015,OUT045,Tier 2,Small,Supermarket Type1,0.033970,19.60,55.1614,5.0

In [3]:
df.shape

(8523, 12)

In [4]:
df.columns

Index(['Item Fat Content', 'Item Identifier', 'Item Type',
       'Outlet Establishment Year', 'Outlet Identifier',
       'Outlet Location Type', 'Outlet Size', 'Outlet Type', 'Item Visibility',
       'Item Weight', 'Sales', 'Rating'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item Fat Content           8523 non-null   str
 1   Item Identifier            8523 non-null   str
 2   Item Type                  8523 non-null   str
 3   Outlet Establishment Year  8523 non-null   int64
 4   Outlet Identifier          8523 non-null   str
 5   Outlet Location Type       8523 non-null   str
 6   Outlet Size                8523 non-null   str
 7   Outlet Type                8523 non-null   str
 8   Item Visibility            8523 non-null   float64
 9   Item Weight                7060 non-null   float64
 10  Sales                      8523 non-null   float64
 11  Rating                     8523 non-null   float64
dtypes: float64(4), int64(1), str(7)
memory usage: 799.2 KB

In [7]:
df.describe()

,Outlet Establishment Year,Item Visibility,Item Weight,Sales,Rating
count,8523.000000,8523.000000,7060.000000,8523.000000,8523.000000
mean,2016.450546,0.066132,12.857645,140.992783,3.965857
std,3.189396,0.051598,4.643456,62.275067,0.605651
min,2011.000000,0.000000,4.555000,31.290000,1.000000
25%,2014.000000,0.026989,8.773750,93.826500,4.000000
50%,2016.000000,0.053931,12.600000,143.012800,4.000000
75%,2018.000000,0.094585,16.850000,185.643700,4.200000
max,2022.000000,0.328391,21.350000,266.888400,5.000000

In [33]:
df.duplicated().sum()/len(df)*100

np.float64(0.0)

In [9]:
df.isnull().sum()

Item Fat Content                0
Item Identifier                 0
Item Type                       0
Outlet Establishment Year       0
Outlet Identifier               0
Outlet Location Type            0
Outlet Size                     0
Outlet Type                     0
Item Visibility                 0
Item Weight                  1463
Sales                           0
Rating                          0
dtype: int64

In [10]:
df.isnull().mean()*100

Item Fat Content              0.000000
Item Identifier               0.000000
Item Type                     0.000000
Outlet Establishment Year     0.000000
Outlet Identifier             0.000000
Outlet Location Type          0.000000
Outlet Size                   0.000000
Outlet Type                   0.000000
Item Visibility               0.000000
Item Weight                  17.165317
Sales                         0.000000
Rating                        0.000000
dtype: float64

In [12]:
df["Item Weight"]=df["Item Weight"].fillna(df["Item Weight"].mean())

In [13]:
df.isnull().sum()

Item Fat Content             0
Item Identifier              0
Item Type                    0
Outlet Establishment Year    0
Outlet Identifier            0
Outlet Location Type         0
Outlet Size                  0
Outlet Type                  0
Item Visibility              0
Item Weight                  0
Sales                        0
Rating                       0
dtype: int64

In [24]:
col = df.columns
df.columns

Index(['Item Fat Content', 'Item Identifier', 'Item Type',
       'Outlet Establishment Year', 'Outlet Identifier',
       'Outlet Location Type', 'Outlet Size', 'Outlet Type', 'Item Visibility',
       'Item Weight', 'Sales', 'Rating'],
      dtype='str')

In [31]:
for i in col:
    print(df[i].unique(),"\n")

<StringArray>
['Regular', 'Low Fat']
Length: 2, dtype: str

<StringArray>
['FDX32', 'NCB42', 'FDR28', 'FDL50', 'DRI25', 'FDS52', 'NCU05', 'NCD30',
 'FDW20', 'FDX25',
 ...
 'DRO59', 'NCW05', 'NCI55', 'FDQ33', 'FDB46', 'FDQ60', 'FDF38', 'FDU60',
 'NCX53', 'FDE52']
Length: 1559, dtype: str

<StringArray>
['Fruits and Vegetables',    'Health and Hygiene',          'Frozen Foods',
                'Canned',           'Soft Drinks',             'Household',
           'Snack Foods',                  'Meat',                'Breads',
           'Hard Drinks',                'Others',                 'Dairy',
             'Breakfast',          'Baking Goods',               'Seafood',
         'Starchy Foods']
Length: 16, dtype: str

[2012 2022 2016 2014 2015 2020 2011 2018 2017]

<StringArray>
['OUT049', 'OUT018', 'OUT046', 'OUT013', 'OUT045', 'OUT017', 'OUT010',
 'OUT027', 'OUT035', 'OUT019']
Length: 10, dtype: str

<StringArray>
['Tier 1', 'Tier 3', 'Tier 2']
Length: 3, dtype: str

<StringArray>
['Medium', 'Small', 'High']
Length: 3, dtype: str

<StringArray>
['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
 'Supermarket Type3']
Length: 4, dtype: str

[0.1000135  0.00859605 0.02589649 ... 0.03470581 0.02757094 0.10771483]

[15.1        11.8        13.85       12.15       19.6         8.89
 19.7        20.75       12.85764518 18.85       17.1        16.35
 20.25       17.85       19.2        12.1         6.85       17.25
 16.         13.35        6.695      16.6         6.92        5.82
 14.8        10.1         7.67       15.6         9.31       13.15
 16.25        6.75       10.5         9.3        18.1        17.5
  7.975      10.          8.93        7.3         7.93       15.35
 19.35        9.5         5.88        8.88       10.6         6.13
  6.38        9.195      11.3        12.6        19.1         9.8
  7.905      10.8        15.5        20.7         8.         19.5
 14.         11.6        10.195      13.65        9.6        10.695
 12.3        11.395      12.35       20.6         6.425       7.
 16.5        13.1        16.1        15.         17.6        19.25
 20.35        6.17       17.7        18.6        15.85        9.395
 21.1         8.1        11.35       11.5         7.42       17.35
  5.34        6.385      12.         14.1         8.06       13.8
  9.065      14.3         5.98       14.7        19.85        6.775
  8.42       19.75       12.85        5.          5.73        7.81
 14.35        6.465       7.5         7.72        8.185       5.175
  5.4        18.75        6.36       14.6        21.25       17.75
 15.2        18.2         5.46       17.2        20.         20.1
  7.35        5.15        6.61       10.3        13.5         7.52
 20.2         7.155       7.84        8.77        7.645      16.75
  7.27        4.785       7.655       7.96       20.5         5.32
 14.5         8.395      21.         15.7         6.715      11.65
  8.71        5.63        5.48       10.895       8.01        8.39
 17.         12.65       18.7         5.425      12.8        18.5
 16.85       18.          5.765      15.25       16.7        20.85
 18.35        8.51        6.865      14.85       13.         18.25
  8.76        5.825       8.275       9.06        7.97        9.695
  6.115       6.785       9.         21.2         7.855       6.65
  6.71        8.31        6.235       4.59        7.63        8.935
  7.07        7.785       7.475       6.8         5.92       11.1
  6.67        9.1         8.3        12.5         6.03        7.145
  6.365       6.32        6.885      10.395       8.5         8.27
 14.15        7.36        7.825       5.51        7.51        8.895
 13.3         5.78        7.02        8.52        6.055       7.285
  5.655       6.78        7.26        6.96        5.035       8.26
  6.635       9.27        7.035       5.5         7.895       6.98
  5.465       8.695      13.6         6.57       19.         11.85
  4.635       5.19        6.405      16.2         8.115       8.35
  7.59        5.095       5.155       7.685       8.97        8.975
  6.675       7.075       8.615      15.75        7.935       6.655
  5.75        8.63        5.325       7.71        9.035       6.44
  7.235      11.          7.21       10.65        8.365       5.945
  6.965       6.215       8.315       6.825       8.6         8.75
  9.285       6.59        6.445       6.11        5.985       7.39
  6.48       11.15        6.155       7.6         8.575       7.85
  7.435       8.96        6.985       5.59        7.55        9.21
  8.85        7.445       7.365       8.645      15.15        7.05
  7.64        8.21        8.235       6.26        6.63        7.09
 21.35        8.905       5.485       6.3         6.86        7.47
  9.895       5.925       5.695       8.985       6.15        8.775
 14.65        8.43        6.195       7.945       4.555       6.765
  7.75        8.84        6.46        8.05        6.615       5.675
  8.155      10.85        4.805       5.26        6.135       8.18
  5.8         4.88        7.105       9.105       5.94        7.405
  5.785       6.55        6.76        5.305       6.305       9.17
  6.175       7.725       7.535       8.38        6.935       8.355
  8.325       4.61        6.895       7.31        8.68        7.1
  8.02        7.17       15.3         6.035       7.22        6.905
  5.365       6.89       14.75        5.905       7.68        5.86
  9.13        7.76        5.635       4.905       6.095       7.325
  5.615       5.845       7.565       7.485       8.67        5.885
  5.11        5.44        5.405       8.945       4.92        5.03
  6.28        6.575       4.615       7.06        6.325       6.69
  6.42        7.315       8.785       8.485       7.575       6.4
  7.865       6.52        8.655       9.42        8.195       5.21
  6.525       7.56        8.8         7.605       7.89        7.275
  5.735       8.92      ]

[145.4786 115.3492 165.021  ... 241.6828  97.8752 112.2544]

[5.  4.9 4.8 4.7 4.6 4.5 4.4 4.3 4.2 4.1 4.  3.9 3.8 3.7 3.6 3.5 3.4 3.3
 3.2 3.1 3.  2.9 2.8 2.7 2.6 2.5 2.4 2.3 2.2 2.1 2.  1.9 1.8 1.7 1.5 1.4
 1.3 1.2 1. ]

In [20]:
df["Item Fat Content"].unique()

<StringArray>
['Regular', 'Low Fat', 'low fat', 'LF', 'reg']
Length: 5, dtype: str

In [22]:
df["Item Fat Content"]=df["Item Fat Content"].replace({'reg':'Regular','LF':'Low Fat','low fat':'Low Fat'})

In [23]:
df["Item Fat Content"].unique()

<StringArray>
['Regular', 'Low Fat']
Length: 2, dtype: str

In [32]:
df.dtypes

Item Fat Content                 str
Item Identifier                  str
Item Type                        str
Outlet Establishment Year      int64
Outlet Identifier                str
Outlet Location Type             str
Outlet Size                      str
Outlet Type                      str
Item Visibility              float64
Item Weight                  float64
Sales                        float64
Rating                       float64
dtype: object

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item Fat Content           8523 non-null   str
 1   Item Identifier            8523 non-null   str
 2   Item Type                  8523 non-null   str
 3   Outlet Establishment Year  8523 non-null   int64
 4   Outlet Identifier          8523 non-null   str
 5   Outlet Location Type       8523 non-null   str
 6   Outlet Size                8523 non-null   str
 7   Outlet Type                8523 non-null   str
 8   Item Visibility            8523 non-null   float64
 9   Item Weight                8523 non-null   float64
 10  Sales                      8523 non-null   float64
 11  Rating                     8523 non-null   float64
dtypes: float64(4), int64(1), str(7)
memory usage: 799.2 KB

In [36]:
df.to_csv("Blinkit Grocery data.csv")